app:
  http_port: 9909
  http_addr: "0.0.0.0"
  max_header_size: 1 # 单位 m
  read_timeout: 60 # 单位 s
  read_header_timeout: 60 # 单位 s
  write_timeout: 60 # 单位 s
  tls: false # true | false
  cert_file: "config/www.ikubeops.local_chain.crt"
  key_file: "config/www.ikubeops.local_key.key"
  shutdown_timeout: 60
  language: "zh"

logger:
  output: "console" # console | file
  format: "console" # json | console
  level: "debug" # debug | info | warn | error
  dev: false # true | false
  file_path: "logs/" #
  max_size: 50 # 单位 m
  max_age: 30
  max_backups: 5

mysql:
  host: "172.16.1.61"
#  host: "127.0.0.1"
  password: "123456"
#  password: "Ikubeops@1998"
  db_name: "gin_xjob"
#  db_name: "demo"
#  port: 3306
  port: 3307
  user: "root"
  max_open_conns: 200
  max_idle_conns: 100
  level: "Info"  # Error, Warn. Info
  opts: "charset=utf8mb4&parseTime=True&loc=Local&&timeout=10s"
  log-to-file: true
  enable: true # true | false

redis:
#  host: "127.0.0.1"
  host: "172.16.1.61"
  password: "123456"
#  password: "Ikubeops@1998"

  port: 6379
  db: 0
  pool_size: 100
  enable: true # true | false
